# Server
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.info-title=Real-Time News Aggregation API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=GraphQL + REST APIs for India News using Quarkus + Camel + Kafka + OpenSearch
quarkus.smallrye-openapi.path=/openapi

# GraphQL UI
quarkus.smallrye-graphql.ui.always-include=true
quarkus.smallrye-graphql.ui.path=/graphql-ui
quarkus.smallrye-graphql.root-path=/graphql

# OpenSearch
quarkus.elasticsearch.hosts=localhost:9200

# Kafka
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.news-out.connector=smallrye-kafka
mp.messaging.outgoing.news-out.topic=news-articles
mp.messaging.outgoing.news-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.news-in.connector=smallrye-kafka
mp.messaging.incoming.news-in.topic=news-articles
mp.messaging.incoming.news-in.group.id=news-consumer-group
mp.messaging.incoming.news-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.news-in.auto.offset.reset=earliest

# News API Keys
news.api.newsapi.base-url=https://newsapi.org/v2
news.api.newsapi.api-key=d240b84a0ac2422a9f1b54f67bf61a99
news.api.newsapi.country=in
news.api.newsapi.page-size=20

news.api.gnews.base-url=https://gnews.io/api/v4
news.api.gnews.api-key=b7a00ae58a27985155199a2ca5797f68
news.api.gnews.country=in
news.api.gnews.lang=en
news.api.gnews.max=10

# Fetch interval (5 min)
news.fetch.interval-ms=300000
news.opensearch.index=news-articles

# Logging
quarkus.log.level=INFO
quarkus.log.category."news.com".level=DEBUG

# Health
quarkus.smallrye-health.ui.always-include=true

# GitHub India News API
news.api.github.base-url=https://raw.githubusercontent.com/theroyakash/newsapis/main/india_news.json
